### ISSUE TITLE
can not add to unity

### ISSUE THREAD

**Issue by a340523052** [PureMVC/puremvc-csharp-multicore-framework#5] opened 2020-06-25 04:01 UTC
can not add to unity

**Comment by saadshams** [comment] 2020-06-30 19:01
Please provide more details, screenshots, etc.

**Comment by a340523052** [comment] 2020-07-01 06:27
![image](https://user-images.githubusercontent.com/25296417/86210280-eb028e80-bba6-11ea-9f4f-c6ead76f2b30.png)
![image](https://user-images.githubusercontent.com/25296417/86210290-efc74280-bba6-11ea-8e0d-6dc4325a9e93.png)

**Comment by a340523052** [comment] 2020-07-01 06:28
![image](https://user-images.githubusercontent.com/25296417/86210346-0a012080-bba7-11ea-87df-77521cb5462b.png)
![image](https://user-images.githubusercontent.com/25296417/86210381-1dac8700-bba7-11ea-8c57-0f29cf59d3a9.png)

**Comment by scc172fly** [comment] 2020-07-22 10:59
It needs some small changes. It's easy to change.

**Comment by saadshams** [comment] 2020-07-24 02:35
Can you explain about those changes or better fork and implement those changes for a review?

**Comment by saadshams** [comment] 2020-07-27 23:43
I just testing with compiling the source code, building a dll and then copying it to the project/Assets/Plugins folder. Unity was able to detect and load it. 

Then I created an empty node and assigned it a script and it executed fine. I think the problem is with copying the sources to the unity. Attached screenshots.

![Screen Shot 2020-07-27 at 7 40 56 PM](https://user-images.githubusercontent.com/703661/88602768-6db12900-d041-11ea-95ba-fd97eaf4f81d.png)

![Screen Shot 2020-07-27 at 7 42 55 PM](https://user-images.githubusercontent.com/703661/88602782-730e7380-d041-11ea-9905-3f4e0066593c.png)


![Screen Shot 2020-07-27 at 7 28 03 PM](https://user-images.githubusercontent.com/703661/88602543-009d9380-d041-11ea-90c4-859a69aee572.png)

**Closed as completed by saadshams** 2020-07-27 23:43 UTC
